spring.application.name=gym_CRM_system1
trainees.file.path=src/main/resources/data/trainees.txt
trainers.file.path=src/main/resources/data/trainers.txt
trainings.file.path=src/main/resources/data/trainings.txt