spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_stg
spring.datasource.username=tato
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.epam.gym_crm_system1=INFO
logging.level.org.hibernate.SQL=INFO