spring.application.name=gym_CRM_system1
spring.profiles.active=local

trainees.file.path=src/main/resources/data/trainees.txt
trainers.file.path=src/main/resources/data/trainers.txt
trainings.file.path=src/main/resources/data/trainings.txt

server.port=8080

spring.jpa.open-in-view=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Gym CRM System
info.app.description=Gym CRM application with Spring Boot Actuator
info.app.version=1.0.0

jwt.secret=paeroithjlkisbvneirutysbhertishe
jwt.expiration-ms=3600000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.circuitbreaker.instances.trainerWorkloadService.sliding-window-size=5
resilience4j.circuitbreaker.instances.trainerWorkloadService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.trainerWorkloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.trainerWorkloadService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.trainerWorkloadService.permitted-number-of-calls-in-half-open-state=2

resilience4j.timelimiter.instances.trainerWorkloadService.timeout-duration=3s
resilience4j.timelimiter.instances.trainerWorkloadService.cancel-running-future=true