spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health,info,prometheus

logging.level.org.epam.gym_crm_system1=INFO
logging.level.org.hibernate.SQL=WARN