spring.application.name=gym_CRM_system1
spring.profiles.active=local

trainees.file.path=src/main/resources/data/trainees.txt
trainers.file.path=src/main/resources/data/trainers.txt
trainings.file.path=src/main/resources/data/trainings.txt

server.port=8080

spring.jpa.open-in-view=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Gym CRM System
info.app.description=Gym CRM application with Spring Boot Actuator
info.app.version=1.0.0

jwt.secret=paeroithjlkisbvneirutysbhertishe
jwt.expiration-ms=3600000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# ActiveMQ Messaging
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}

app.messaging.trainer-workload-queue=trainer.workload.queue