spring.application.name=trainer-workload-service

server.port=8081

# MongoDB
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/trainer_workload_db}
spring.data.mongodb.auto-index-creation=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT
jwt.secret=paeroithjlkisbvneirutysbhertishe

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

# ActiveMQ Messaging
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.initialRedeliveryDelay=500}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
spring.jms.listener.session.transacted=true

app.messaging.trainer-workload-queue=trainer.workload.queue